name: Test on Ubuntu
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.1', '3.0', '2.7', '2.6' ]
        os:
          - ubuntu-latest
    name: Ruby ${{ matrix.ruby }} unit testing on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: unit testing
      env:
        CI: true
      run: |
        gem install bundler rake
        bundle install --jobs 4 --retry 3
        bundle exec rake test
