name: Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.4', '3.3', '3.2' ]
        os: [ 'ubuntu-latest', 'macOS-latest', 'windows-latest' ]
    name: Ruby ${{ matrix.ruby }} unit testing on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: unit testing
      env:
        CI: true
      run: |
        bundle exec rake test
